### ISSUE TITLE
dist里面没有/dist/index.js 

### ISSUE THREAD

**Issue by relzhong** [Nbsaw/pyfl#1]
yarn下来不能require， 应该是dist里面没有/dist/index.js

**Comment by Nbsaw** [comment]
抱歉 之前改的时候忘记 改过来了。我重新发一下。

**Comment by relzhong** [comment]
nodejs不能正常require, 试试改一下webpack的输出为umd形式, https://www.webpackjs.com/configuration/output/#output-librarytarget

**Comment by Nbsaw** [comment]
@relzhong 更新一下包 试试

``` js
const pyfl = require('pyfl').default;
```
