### ISSUE TITLE
安装依赖后找不到

### ISSUE THREAD

**Issue by Michel-Yang** [Nbsaw/pyfl#4]
项目中安装依赖后运行报如下错误
![微信图片_20190428112413](https://user-images.githubusercontent.com/19601873/56858364-315ccc00-69ab-11e9-831f-2c039894e4d3.png)

**Comment by Nbsaw** [comment]
@Michel-Yang 嗨 已修复了这个问题 更新一下依赖

**Comment by Michel-Yang** [comment]
已解决

**Comment by Nbsaw** [comment]
@Michel-Yang 感谢提出问题
